### ISSUE TITLE
Investigate MacOS compatibility

### ISSUE THREAD

**Issue by loiccoyle** [loiccoyle/zsh-github-copilot#1]
I would like this plugin to be compatible with Mac flavoured Linux/Unix, but I don't have a mac to test it on.

**Comment by Akagi201** [comment]
on my macos, I should rename the file to `zsh-github-copilot.plugin.zsh` to make omz recognize the plugin.

**Comment by loiccoyle** [comment]
I'll rename the file on `main`, thanks for the feedback. Can you confirm that the plugin works as expected on MacOS?

**Comment by Akagi201** [comment]
Yes, it works on macOS. I already used it.
