### ISSUE TITLE
Red Triangle Question Mark

### ISSUE THREAD

**Issue by nmcbride** [loiccoyle/zsh-github-copilot#10]
For some reason, I am not 100% sure why, I do not get any spinners or anything. 

Just a read triangle with a question mark as a placeholder.

**Comment by loiccoyle** [comment]
Are you on linux or mac? And can you share a screenshot?

**Comment by nmcbride** [comment]
I am on Fedora. I have attached a screenshot.

![Screenshot from 2024-10-07 10-19-11](https://github.com/user-attachments/assets/e92c3265-7807-4fc5-96fe-328a26a8b8ba)

**Comment by nmcbride** [comment]
It is working, it is just the icon that is not.

 My setup may be a little unique compared to what you are used to, I'm on Fedora Silverblue and have Nix installed with zsh, oh-my-zsh and your plugin installed through home-manager. :)

**Comment by loiccoyle** [comment]
ok can your terminal display these characters `⣾⣽⣻⢿⡿⣟⣯⣷`?

**Comment by nmcbride** [comment]
So it is definitely a me issue, just not sure why. 

The first time zsh loads no, those characters do not work. 

If I spawn zsh again, then they work...
```
➜  ~ echo -e '\u28fe' 
zsh: character not in range
➜  ~ zsh
➜  ~ echo -e '\u28fe' 
⣾
```

**Comment by loiccoyle** [comment]
My only guess is that maybe the locale isn't configured properly?

**Comment by loiccoyle** [comment]
I'll close this issue as it isn't related to this repo, feel free to add your fix in case someone else has the same issue.
