### ISSUE TITLE
Possibility to disable the check for gh or copilot extension on startup?

### ISSUE THREAD

**Issue by zzh8829** [loiccoyle/zsh-github-copilot#11]
Hi I just started using this extension it works amazingly well. 
However in my environment gh and gh copilot cli are not available during the zsh plugin initialization phase. They are added into my path later in the zshrc.
So right now I cannot use this extension as is. Is there a way to disable the validation error?

It would make more sense for the validation to run when the user invoke widgets for the first time.

**Comment by cosy363** [comment]
Move your $PATH update before plugin initialization in `.zshrc`:

```
export PATH="$PATH:/path/to/gh"
...
plugins=(git, zsh-github-copilot, ...)
...
```

This ensures `gh `is available during plugin initialization, avoiding the error. 😊

**Comment by loiccoyle** [comment]
Hi, sorry I missed this issue. Did you manage to figure it out? If not, I could add a way to disable the checks all together.

**Comment by zzh8829** [comment]
that would not be very easy since my clis are managed by some combination of brew, asdf, nvm you name it, it would be hard to make them available before zsh initialization.

**Comment by loiccoyle** [comment]
Ok, would adding a env variable which skips the checks solve your issue? Which means that you could add `export ZSH_GH_COPILOT_NO_CHECK=1` to your `.profile` file to disable the check. Would that work for you?

**Comment by zzh8829** [comment]
> Ok, would adding a env variable which skips the checks solve your issue? Which means that you could add `export ZSH_GH_COPILOT_NO_CHECK=1` to your `.profile` file to disable the check. Would that work for you?

that would be a great solution!

**Comment by loiccoyle** [comment]
Should be good now, add `export ZSH_GH_COPILOT_NO_CHECK=1` to your `.profile`.
