### ISSUE TITLE
Combined history and copilot autocompletion

### ISSUE THREAD

**Issue by MikaelElkiaer** [loiccoyle/zsh-github-copilot#3]
Hi, great work on this - nice and simple utility.

However, I did stumble upon it while looking for something slightly different.
Have you looked into, or considered, if it would be possible to do copilot-based autocompletion, based on local zsh history?
It should probably be a suggestion that can be completed - similar to zsh-autosuggestions (while writing this, I did find [this issue](https://github.com/zsh-users/zsh-autosuggestions/issues/736)).

**Comment by loiccoyle** [comment]
Thanks!

This project is basically a wrapper for the `gh copilot` cli, it doesn't do anything `zsh-autosuggestions` related. No I haven't really looked into llm based autosuggestions at all, and it isn't something that I would implement in this project.

Technically, one could feed the `gh copilot` extension a couple lines of the zsh history and ask for the next command but this raises some security concerns so it isn't something I want to touch. I would suggest using the fork in the issue you mentioned, at least it seems the llm is running locally (as far as I can tell) which alleviates my concerns.
