### ISSUE TITLE
"Ctrl-\" is a terrible suggestion :)

### ISSUE THREAD

**Issue by timcharper** [loiccoyle/zsh-github-copilot#8]
`Ctrl-\` sends `SIGQUIT` to the current running program. I don't think it's a good idea to recommend users get in the habit of hitting it.

It might be better to recommend:

```
bindkey '^[|' zsh_gh_copilot_explain  # bind Alt+shift+\ to explain
bindkey '^[\' zsh_gh_copilot_suggest  # bind Alt+\ to suggest
```

**Comment by loiccoyle** [comment]
Woops, indeed that isn't great. I'll change it. Thanks!
